### ISSUE TITLE
Not able to configure TwoFactorAuth.net with Authenticator Apps [Not sure its an issue or limitation]

### ISSUE THREAD

**Issue by nareshkumarhk** [RobThree/TwoFactorAuth.Net#1]
Hi,

Am currently trying to use TwoFactorAuth.net with Authenticator apps but failing to do so if I try to customize the constructor. 

Example
If am trying to create an instance with the following constructor
 ```
New TwoFactorAuth(AppName,
            OTPLength,
            Period,
            Algorithm.SHA256,
            New ISL.Security.Provider.BasicQRCodeProvider())
```

Issue 1:
If OTPLength is set to 8 or so, the authenticator app only generates 6 digits.
Issue 2:
If Period is set to 4 mins or so, the authenticator app always expires in 30 seconds.

If we use the default construtor - everything falls in place
 `New TwoFactorAuth(AppName)`
Where it takes default values of 6 digits and 30 seconds

PS
Tried Google and Microsoft Authenticator app

Please help me with the same.

**Comment by RobThree** [comment]
My _Best Guess_™ is that the problem lies in `ISL.Security.Provider.BasicQRCodeProvider`. Can you scan the QR code with something like [QR Reader](https://itunes.apple.com/us/app/qr-reader-for-iphone/id368494609?mt=8) and tell me what the content of the QR code is? Or can you post a QR code here?

**Comment by nareshkumarhk** [comment]
Just figured out... Its limitation with the authenticators, it does not take into account of the digts/period fields.
FreeOTP Authenticator app seems to take those parameters into account 

More info:
https://github.com/google/google-authenticator/issues/521
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

![image](https://cloud.githubusercontent.com/assets/3511769/19434404/d5dbb3a0-9482-11e6-9688-1866b5f29b04.png)

**Comment by RobThree** [comment]
Hmmm, I seem to recall Google Authenticator worked fine with 8 digit but I guess I'm mistaken. MS Authenticator I haven't tried.
