### ISSUE TITLE
Instagram TOTP Codes are Invalid

### ISSUE THREAD

**Issue by jbellomy97** [RobThree/TwoFactorAuth.Net#15]
Good afternoon,

I'm trying to make TwoFactorAuth.NET work with Instagram. When enabling 2FA Instagram gives you a Base32 string of characters. Using this string here, I would expect the codes TwoFactorAuth.NET would generate accurate 6 digit TOTP responses:

```
Dim TFA As New TwoFactorAuth
Dim Code As String = TFA.GetCode("xxxx")
Call Console.WriteLine("[*] TOTP 2FA Code: " & Code)
```

Even after iterating through each timezone when trying to generate codes the TwoFactorAuth.NET codes are invalid. The codes are also different than what Google Authenticator when generating codes at the same time for the same Base32 string, and those codes work. I have a .Net solution and an exemplar account I would be happy to give you access to privately in support of any troubleshooting you might be able to help me with.

**Comment by RobThree** [comment]
I'm sorry, I can't make heads nor tails from your question.

What does TwoFactorAuth.Net have to do with Instagram? Why are you iterating timezones? Are you even sure your time is correct? What is your `discrepancy` setting? Have you read [the README](https://github.com/RobThree/TwoFactorAuth.Net#step-2-verify-secret-shared-key)?

> I have a .Net solution and an exemplar account I would be happy to give you access to privately in support of any troubleshooting you might be able to help me with.

Always provide sample code to reproduce an issue immediately when opening an issue instead of having people ask for it. I'm not interested in accessing private repositories and I don't do 'private support' and 'troubleshooting' (e.g. debugging your code). Simply strip your issue down to the bare minimum (e.g. a testcase) to reproduce and post it here. That way, [when I help _you_ I _also_ help others that might face similar issues](https://xkcd.com/979/).

**Comment by jbellomy97** [comment]
Rob,

Instagram allows you to set a TOTP secret key to generate codes with a TOTP generator. TFA.NET being one of those generators, I expected it to properly generate codes that Instagram would accept given the TOTP secret key that Instagram supplies.

I see you found the (old) 2FA secret, username, and test password I was using with another developer. If I were to give you the new TOTP secret you would then have exactly the bare minimum test case I'm trying to troubleshoot. Before opening the issue I read your README and would point out that I'm not using `VerifyCode()`, the only place your README mentions `discrepancy`. I've had two other people look at it without being able to figure out why Google Authenticator would generate codes differently than TFA.NET given the three lines you see above.

**Comment by RobThree** [comment]
Timezones are irrelevant since TOTP codes are based on UTC.

**Comment by jbellomy97** [comment]
That code, in case you're interested, is located here: https://github.com/jbellomy97/Testagram/blob/9037f57116314cac56a248a4678c804e5f1cc456/Instagram.vb#L27 (same project, different module).

**Comment by RobThree** [comment]
> That code, in case you're interested, is located here: https://github.com/jbellomy97/Testagram/blob/9037f57116314cac56a248a4678c804e5f1cc456/Instagram.vb#L27 (same project, different module).

I saw, but you can't expect me to go over it and debug it all. I just verified (see [my edit](https://github.com/RobThree/TwoFactorAuth.Net/issues/15#issuecomment-683351929)) and TwoFactorAuth.Net produces the exact same codes as other TOTP apps.

**Comment by jbellomy97** [comment]
Rob, thank you - it's now generating 2FA codes that the website accepts and that equal Microsoft Authenticator. I think I'm good here, thanks for your time.

**Comment by RobThree** [comment]
Please have the courtesy to [let me/us know what the problem was](https://xkcd.com/979/). I've put effort into this, now you please do the same.

**Comment by jbellomy97** [comment]
Honestly, I couldn't tell you. Using a different account I had it generate
new 2FA material and plugged it into Microsoft Authenticator. I took that
material and put it in the same call to TFA. I wonder if with all the
banging I've been doing on it the original account is messed up on the
backend because it works just fine taking the new 2FA material generated.

**Comment by RobThree** [comment]
Next time please verify these kind of things before wasting someone else's precious time 😉
