### ISSUE TITLE
Convert to .NET Standard

### ISSUE THREAD

**Issue by andrewlock** [RobThree/TwoFactorAuth.Net#2]
Hi, I'm currently working on a .NET Core project, and I was interested in using TwoFactorAuth.Net as a two factor auth provider.

I was wondering if you'd be interested in converting the project to a .NET Standard project, as it would make the process much easier.

The biggest problem as-is is the use of the `System.Drawing` package . There's not a direct replacement for this that works cross-platform, though their are alternatives. 

It looks like `System.Drawing` is only required if you're actually manipulating the QR codes, which aren't critical. There's a couple of options there, but possibly the easiest is just to cross-compile the app, and only include the `System.Drawing` methods in the `net461` version

If you're happy to go this route, we'd probably need to convert to the new csproj style in VC2017.

I'm happy to do the bulk of the conversion work if this is something you're interested in, but just wanted to gauge your feelings on it first.

**Comment by RobThree** [comment]
I would surely be interested; but since I haven't done much .Net core yet I'm not sure what the best route would be. The `System.Drawing` use is mostly for the `Color` struct. That should easily be swapped out with a simple "own" class or something. I would like to keep backwards compatibility as much as possible so cross-compiling for `net461` and .Net core would be a good idea I guess. Another option would be to break backwards compatibility *once* removing all non-Core compatible stuff. No idea how much work that would involve but I guess not _that_ much?

**Comment by andrewlock** [comment]
That's great, - in my mind the easiest route is to convert the project to the new csproj format. With cross compiling there'd be no need to break back compat for the `net45` library - the net standard library would just have a smaller API surface. 

If `Color` really is all System.Drawing is needed for, would definitely suggest just pulling it in to the project (or as they are converted to hex, just expose the hex and remove the System.Drawing dependency altogether). 

The other major APIs that are different in netstandard are the `RemoteValidationCallback` (they removed it as it's too easy to abuse), and `WebRequestHandler` has not been ported. 

As it is, I'm not entirely sure the best way to handle these. I'd be inclined to just use the default handler, but I'm not sure of the implications of that, as I've never actually use the `WebRequestHandler`!

**Comment by RobThree** [comment]
See bdc70d66af8c398b3ca56ef96a230e906f52b710 and [1.3.0](https://www.nuget.org/packages/TwoFactorAuth.Net/1.3.0). Does this work for you?

**Comment by GeekyMonkey** [comment]
I tried 1.3.0 and it's not working in my .NET Core 2 project. There is a function used that's in Framework but missing in Core.  It's a simple one-liner that just seems to have gotten overlooked.

https://github.com/dotnet/corefx/issues/22626

I've issued a pull request to fix this problem in TwoFactorAuth.net.  It's working in my project from my fork.

**Comment by RobThree** [comment]
Thanks! See PR for more.

**Comment by RobThree** [comment]
Just double-checking: does [this](https://github.com/RobThree/TwoFactorAuth.Net/blob/master/TwoFactorAuth.Net/Providers/Rng/HashRngProvider.cs#L23) work?

`HashAlgorithm.Create("HMACSHA256");` in [Providers/Rng/HashRngProvider.cs](https://github.com/RobThree/TwoFactorAuth.Net/blob/master/TwoFactorAuth.Net/Providers/Rng/HashRngProvider.cs)

**Comment by GeekyMonkey** [comment]
Sorry for the delay. Day job nonsense. :) 

Nuget package v1.3.1 looks good to me.  I ran the .[NET Portability Analyzer ](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) on it and it's all green for Core 2.0, Framework 4.7.1, and .Net Standard 2.0

Not OK for .Net Standard 1.6 or below, but I think that's expected.

Maybe you could adjust the dependencies list on the readme so more people can avail of this goodness.

**Comment by RobThree** [comment]
> Maybe you could adjust the dependencies list on the readme so more people can avail of this goodness.

👍 Good idea.

Thanks for the feedback / testing!
