### ISSUE TITLE
How to display the QR Code in MVC view

### ISSUE THREAD

**Issue by JoopStringer** [RobThree/TwoFactorAuth.Net#24]
When I try to use the code from the readme, it gives error "the name 'tfa' doe not exist"

```
// Display QR code to user
<p>Scan the following image with your app:</p>
<p><img src="@tfa.GetQrCodeImageAsDataUri("Bob Ross", secret)"></p>

```
When I try to use the code in a controller and then send it to MVC view, I get error on tfa.GetQRCodeImageAsDataUri...
"System.Net.WebException: 'The request was aborted: Could not create SSL/TLS secure channel."

De aanvraag is afgebroken: Kan geen beveiligd SSL/TLS-kanaal maken. bij System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request) bij System.Net.WebClient.DownloadData(Uri address) bij TwoFactorAuthNet.Providers.Qr.BaseHttpQrCodeProvider.DownloadData(Uri address) bij TwoFactorAuthNet.TwoFactorAuth.GetQrCodeImageAsDataUri(String label, String secret, Int32 size) 

Any idea how to fix it ?

```
var tfa = new TwoFactorAuth("Bob Ross");
var secret = tfa.CreateSecret(160);
Session["TFAsecret"] = secret;

ContactTFAModel cm = new ContactTFAModel();
cm.IDKey = IDKey;
cm.URI = tfa.GetQrCodeImageAsDataUri("Bob Ross", secret);
cm.ReturnUrl = ViewBag.ReturnUrl;
return View(cm);
```

**Comment by JoopStringer** [comment]
Found a solution to the problem. Adding the following code before creation of tfa.GetQRCodeImageAsDataUri it works

                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                       | SecurityProtocolType.Tls11
                       | SecurityProtocolType.Tls12
                       | SecurityProtocolType.Ssl3;

See here: https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

**Comment by RobThree** [comment]
This is not a TwoFactorAuth.Net problem, but good you solved it! 👍
