### ISSUE TITLE
How to get the code to manually add to authenticator

### ISSUE THREAD

**Issue by JoopStringer** [RobThree/TwoFactorAuth.Net#25]
Beside the QRcode it would be nice to have the manual code to enter into the Authentication App.
If I send the QR to a phone they can't scan it :-)
So I want to have the code available to enter it manually.

Which function to use ?
Or is it the Secret generated by CreateSecret()

Thanks !

**Comment by RobThree** [comment]
It is the code generated by CreateSecret, you can check that because it's also contained in the QR code.

**Comment by JoopStringer** [comment]
OK, thanks !
