### ISSUE TITLE
Generate URL and code for non-QR option

### ISSUE THREAD

**Issue by DeePanto** [RobThree/TwoFactorAuth.Net#26]
I'm trying to add two factor authentication to my system. We want to support account addition with non-QR options (say, user's camera isn't working so they pick "Enter Code Manually").
On Windows Authenticator, it requires a numeric code, and a URL. I've gone over the documentation and came up short with how to generate these through this library.
What did I miss? And is this even supported?

**Comment by RobThree** [comment]
You can call `CreateSecret()` to create a / the secret that is usually shared in QR form. This is a Base32 encoded string with A-Z 0-9 characters basically which you can type in manually. I'm not familiar with what you're describing ~Windows~ Microsoft Authenticator does, but I can imagine you give a URL that opens the app and passes the secret to the app in a 'query string' kind of way.

**Comment by DeePanto** [comment]
Ah that's totally my bad, I feel silly. I was trying to enter using a Microsoft account. Using the Other Account option did the trick. Thank you for the speedy response, and sorry for the bother!

**Comment by RobThree** [comment]
NP
