### ISSUE TITLE
VerifyCode(secret, code, n, out slice) returns invalid timeslice value

### ISSUE THREAD

**Issue by lellis1936** [RobThree/TwoFactorAuth.Net#5]
The new methods are working great for my application, but there seems to be a bug.
I am getting slice values that are separated by as little as 6 seconds, and they are not multiples of 30 seconds.  Here is some code:
```
 for (; ; )
            {
                Console.Write("Enter the Google code: ");
                string code = Console.ReadLine();
                if (code == "")
                    break;

                if (tfa.VerifyCode(secret, code, 2, out slice))
                {
                    if (slice <= lastMatchingTimeSlice)
                        Console.WriteLine("Code is valid, but you already used it");
                    else
                    {
                        Console.WriteLine("Valid code!");
                        lastMatchingTimeSlice = slice;
                    }
                }
                else
                    Console.WriteLine("Invalid code");

                Console.WriteLine();
            }
```
I assume the timeslice value is supposed to be a unix timestamp rounded down to the previous 30 second boundary, and that it represents the timeslice associated with the matched code.

But I see the following values on one iteration:
```
slice = 1528241471
lastMatchingTimeslice = 1528241465
```
Is this a bug?  What I am seeing is that my code fails to detect  code reuse if the same code is entered twice.

**Comment by RobThree** [comment]
Can you show the code where you create the `tfa` object? Are you sure the period isn't set to 6 seconds?

**Comment by RobThree** [comment]
DAMNED... rushed it too hard. There's a bug indeed... instead of time**slices** it tracks time**stamps**. I'll see what I can do.

**Comment by RobThree** [comment]
Must've been too tired from coding all day. It now returns a time**slice** instead of a time**stamp**.

Update your nuget package and it should be fine. [1.3.3](https://www.nuget.org/packages/TwoFactorAuth.Net/1.3.3)

**Comment by lellis1936** [comment]
Yes, all is well now.  Thank you.
