### ISSUE TITLE
Question:  Are timeslices opaque?

### ISSUE THREAD

**Issue by lellis1936** [RobThree/TwoFactorAuth.Net#6]
The new option to return timeslice after successful validation is great.  I was wondering if a client app could make any assumptions about the value.   For example, I would like to be able to get the datetime associated with the timeslice.  Tentatively, I have coded this:
```
public DateTime GetUtcDateTimeForTimeSlice(long timeslice)
{
    long unixTimeStamp = timeslice * PERIOD;

    // Unix timestamp is seconds past epoch
    System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
    dtDateTime = dtDateTime.AddSeconds(unixTimeStamp);

    return dtDateTime;

}
```
Certainly, not asking for anything new in the library because it's fine as-is, but wondering if you think interpreting the meaning of the timeslice in this way is acceptable.

**Comment by RobThree** [comment]
The period is variable (although, as far as I know, most use the default 30 seconds, I can't remember seeing a different period in the wild besides unittests) so you'll have to make sure you extract / store that value when the client reads the [Key Uri](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#period). If you know the period then, yes, you can calculate the (to within <period>-seconds approximate) datetime associated with the timeslice.

**Comment by lellis1936** [comment]
We always use 30.   Besides, without knowing the right period for a user we couldn't generate a valid codestream anyway.   Not currently storing it, but I don't see it changing and it if did we could add it to the database then...

**Comment by RobThree** [comment]
> Besides, without knowing the right period for a user we couldn't generate a valid codestream anyway

Nobody could 😉 I was referring to making sure you extract the value instead of assuming the value (like Google Authenticate does (did?).
