### ISSUE TITLE
Google's QR generator has gone dark. It should no longer be the default.

### ISSUE THREAD

**Issue by GeekyMonkey** [RobThree/TwoFactorAuth.Net#9]
https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI

I've switched to one of the alternate providers to get our websites back in business.  The google one should no longer be the default.

It would be nice if we could configure multiple providers, and on failure go to the next available option.  Even better would be not having that external dependency.

**Comment by RobThree** [comment]
> I've switched to one of the alternate providers to get our websites back in business. The google one should no longer be the default.

I'll pick a new default.

> It would be nice if we could configure multiple providers, and on failure go to the next available option. 

If I were you I'd implement ANOTHER provider; let's call it a `FallbackProvider`; this could simply implement `IQrCodeProvider` and have an `IEnumerable<IQrCodeProvider>` provided in it's constructor. The implementation could then do all the work trying underlying providers, trying the next on failure etc. Shouldn't be hard to implement.

> Even better would be not having that external dependency.

No problem. You can [implement your own](https://github.com/RobThree/TwoFactorAuth.Net/wiki/How-to-implement-your-own-QR-Code-provider). Simply pick any [QR library](https://www.nuget.org/packages?q=qr+code) and have it generate the images for you.

**Comment by GeekyMonkey** [comment]
Thanks Rob. Sounds like you got it covered.

**Comment by RobThree** [comment]
See [1.3.6](https://www.nuget.org/packages/TwoFactorAuth.Net/1.3.6) and [this commit](https://github.com/RobThree/TwoFactorAuth.Net/commit/4944f19ccfed1c069080723711149e0debf601dc)

**Comment by GeekyMonkey** [comment]
Thanks for the quick turnaround on that Rob. To remove the risk of the API going dark again, I followed your advice and implemented a QR Code provider that doesn't need to call an API. I chose SkiaSharp because I'm deploying to Linux/Docker and this didn't require any extra libs to be installed there.

I've made my provider available as a NuGet package in case anyone else would like to use it. Feel free to link in your docs.

[NuGet](https://www.nuget.org/packages/GeekyMonkey.TwoFactorAuthNetSkiaSharpQrProvider/)
[GitHub](https://github.com/GeekyMonkey/TwoFactorAuthNetSkiaSharpQrProvider)

**Comment by RobThree** [comment]
I've [created a wiki](https://github.com/RobThree/TwoFactorAuth.Net/wiki/3rd-party-providers) and [referred to it from the README](https://github.com/RobThree/TwoFactorAuth.Net/commit/ad9d5818cdb34438a4d0fe98bb720e8d666c2f8d).

Thanks for the heads-up on the issue and thanks for your implementation! 👊
